/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.ufes.p2_pss.view.requestaccess;

import javax.swing.JButton;
import javax.swing.JCheckBox;
import javax.swing.JList;

/**
 *
 * @author Lucas
 */
public class RequestAccessV extends javax.swing.JInternalFrame {

    /**
     * Creates new form SolicitarAcesso
     */
    public RequestAccessV() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cbView = new javax.swing.JCheckBox();
        cbShare = new javax.swing.JCheckBox();
        cbDelete = new javax.swing.JCheckBox();
        btnClose = new javax.swing.JButton();
        btnSolicitar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        listAdmin = new javax.swing.JList<>();

        setTitle("Solicitar acesso");

        cbView.setText("Visualizar");

        cbShare.setText("Compartilhar");

        cbDelete.setText("Excluir");

        btnClose.setText("Sair");

        btnSolicitar.setText("Solicitar");

        jScrollPane1.setViewportView(listAdmin);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSolicitar)
                .addGap(18, 18, 18)
                .addComponent(btnClose)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 140, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cbView)
                        .addGap(12, 12, 12))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(cbShare, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(cbDelete)
                            .addGap(17, 17, 17))))
                .addGap(122, 122, 122))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(36, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(cbView)
                        .addGap(18, 18, 18)
                        .addComponent(cbShare)
                        .addGap(18, 18, 18)
                        .addComponent(cbDelete)
                        .addGap(89, 89, 89)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnClose)
                    .addComponent(btnSolicitar))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnSolicitar;
    private javax.swing.JCheckBox cbDelete;
    private javax.swing.JCheckBox cbShare;
    private javax.swing.JCheckBox cbView;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<String> listAdmin;
    // End of variables declaration//GEN-END:variables

    public JButton getBtnClose() {
        return btnClose;
    }

    public JButton getBtnSolicitar() {
        return btnSolicitar;
    }

    public JCheckBox getCbDelete() {
        return cbDelete;
    }

    public JCheckBox getCbShare() {
        return cbShare;
    }

    public JCheckBox getCbView() {
        return cbView;
    }

    public JList<String> getListAdmin() {
        return listAdmin;
    }
}
