/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.ufes.p2_pss.view.requestaccess;

import javax.swing.JButton;
import javax.swing.JTable;

/**
 *
 * @author Lucas
 */
public class SolicitationsAuth extends javax.swing.JInternalFrame {

    /**
     * Creates new form SolicitationsAuth
     */
    public SolicitationsAuth() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblSolicitation = new javax.swing.JTable();
        btnClose = new javax.swing.JButton();
        btnAccept = new javax.swing.JButton();

        tblSolicitation.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Usuário", "Imagem", "Visualizar", "Compartilhar", "Deletar"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Boolean.class, java.lang.Boolean.class, java.lang.Boolean.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblSolicitation);
        if (tblSolicitation.getColumnModel().getColumnCount() > 0) {
            tblSolicitation.getColumnModel().getColumn(0).setResizable(false);
            tblSolicitation.getColumnModel().getColumn(0).setPreferredWidth(200);
            tblSolicitation.getColumnModel().getColumn(1).setResizable(false);
            tblSolicitation.getColumnModel().getColumn(1).setPreferredWidth(200);
            tblSolicitation.getColumnModel().getColumn(2).setResizable(false);
            tblSolicitation.getColumnModel().getColumn(2).setPreferredWidth(20);
            tblSolicitation.getColumnModel().getColumn(3).setPreferredWidth(20);
            tblSolicitation.getColumnModel().getColumn(4).setPreferredWidth(20);
        }

        btnClose.setText("Fechar");

        btnAccept.setText("Aceitar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 762, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(62, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnAccept)
                .addGap(18, 18, 18)
                .addComponent(btnClose)
                .addGap(19, 19, 19))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 72, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnClose)
                    .addComponent(btnAccept))
                .addGap(27, 27, 27))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAccept;
    private javax.swing.JButton btnClose;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblSolicitation;
    // End of variables declaration//GEN-END:variables

    public JButton getBtnAccept() {
        return btnAccept;
    }

    public JButton getBtnClose() {
        return btnClose;
    }

    public JTable getTblSolicitation() {
        return tblSolicitation;
    }
}
